apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: church-dashboard-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: church-dashboard
    k8s.kuboard.cn/workload: church-dashboard
    kubernetes.io/ingress.class: "devops-vpn-nginx-internal"
    nginx.com/sticky-cookie-services: "serviceName=kuboard srv_id expires=1h path=/"

spec:
  rules:
    - host: dashboard.npool.top
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: church-dashboard
              servicePort: 80
    - host: dashboard.xpool.top
      http: *http_rules
    - host: www.dashboard.npool.top
      http: *http_rules
    - host: www.dashboard.xpool.top
      http: *http_rules
